name: Crates
version: 1.0-SNAPSHOT
main: me.grabsky.crates.Crates
api-version: 1.18
authors: [Grabsky]
depend: [Indigo]
permissions:
  crates.command.crates.*:
    childern:
      crates.command.crates: false
      crates.command.crates.get: false
      crates.command.crates.give: false
      crates.command.crates.giveall: false
      crates.command.crates.reload: false