name: Crates
version: ${project.version}
main: net.skydistrict.crates.Crates
api-version: 1.16
authors: [Grabsky]
depends: [Indigo]
permissions:
  skydistrict.command.crates.*:
    description: 'Access all crates commands'
    childern:
      skydistrict.command.crates: false
      skydistrict.command.crates.reload: false
      skydistrict.command.crates.getcrate: false
      skydistrict.command.crates.give: false
      skydistrict.command.crates.giveall: false
commands:
  crates:
    aliases: ['crate', 'skrzynki']
    permission: 'skydistrict.crates'
    permission-message: '§6§lS§e§lD§8 » §cBrak uprawnień.'