name: Crates
version: ${project.version}
main: me.grabsky.crates.Crates
api-version: 1.17
authors: [Grabsky]
depend: [Indigo]
permissions:
  crates.command.crates.*:
    childern:
      crates.command.crates: false
      crates.command.crates.getcrate: false
      crates.command.crates.give: false
      crates.command.crates.giveall: false
      crates.command.crates.reload: false